### ISSUE TITLE
Clicking the file dialogue shows nothing

### ISSUE THREAD

**Issue by soumyaDghosh** [Nokse22/teleprompter#18]
When I click the open file dialogue button, it opens up nothing. I only get this error dialogue:

```
Gtk-Message: 02:18:20.952: GtkDialog mapped without a transient parent. This is discouraged.
```

Else, the snap package is working, just as it should be,

**Comment by Nokse22** [comment]
I will fix that error. To open a file I use Gnome portals xdg-desktop-portal-gnome so that I don't need any permission, I don't know how it would work with snap.

**Comment by soumyaDghosh** [comment]
That error needs to be fixed I guess, then snap will be fine.

**Comment by Nokse22** [comment]
Ok, I have added all the other app to my account and invited you as a collaborator

**Comment by soumyaDghosh** [comment]
Even the binary name is `mini-text`, why do you register `minitext`? Was that by mistake? Should I try to change it?

**Comment by Nokse22** [comment]
I didn't think it was important, the flathub ID is `io.guthub.nokse22.minitext`

**Comment by Nokse22** [comment]
I made a new release of Teleprompter and the error should be fixed

**Comment by soumyaDghosh** [comment]
Fixed this, by focing `GDK_DEBUG` to portals. In the review queue now
