### ISSUE TITLE
No shortcut on Fedora 38 / Mate

### ISSUE THREAD

**Issue by VieuFou34** [Nokse22/teleprompter#22]
Hi ! 

First, thank you for the software that works very fine and is useful !

I have a problem though, I have installed the app using the app manager named Software (it's from gnome I guess), and I can launch teleprompter from the app manager, but there is no shortcut in my Mate environment. I tried to add one but I am not able to find the software's files.
When I perform a search I get these files (find / -name teleprompter) : 

/var/lib/flatpak/app/io.github.nokse22.teleprompter/x86_64/stable/eceabb3c0a90ddef6ce64a4fd3a6a42040def71b51c27799cd8b67f83dfd27e4/files/bin/teleprompter
/var/lib/flatpak/app/io.github.nokse22.teleprompter/x86_64/stable/eceabb3c0a90ddef6ce64a4fd3a6a42040def71b51c27799cd8b67f83dfd27e4/files/share/teleprompter
/var/lib/flatpak/app/io.github.nokse22.teleprompter/x86_64/stable/eceabb3c0a90ddef6ce64a4fd3a6a42040def71b51c27799cd8b67f83dfd27e4/files/share/teleprompter/teleprompter

But they don't help me creating a shorcut. I'm very noob to Linux so would you like to help me create it in order to avoid entering the app manager to launch Teleprompter please ? 

Thank you very much :)

**Comment by Nokse22** [comment]
Hello sorry for the very late response. The application files are difficult to find because it's a Flatpak. There are some apps to create shortcuts like [Pin App](https://flathub.org/en-GB/apps/io.github.fabrialberio.pinapp) that should help you fix it.
