### ISSUE TITLE
Allow for proportional animation speeds, independent of window and font sizes

### ISSUE THREAD

**Issue by Cuperino** [Nokse22/teleprompter#24]
A common issue in new teleprompter software is that speed must be adjusted differently depending on the size of the typeface and the screen's resolution. Another, related, issue is small speed increments are easily noticeable when the animation starts but increments by the same amount become negligible as speed increases.

My solution to both of these problems is to count speed increments as "steps", then compute the animation speed based on: number of steps, the font-size and the screen's width, since that determines how many words can be seen at a given time.

This can be done in a few ways. On [QPrompt](https://github.com/Cuperino/QPrompt-Teleprompter/blob/51788ebfab4314c3b9e336dd492d3e9d8502a6c6/src/prompter/Prompter.qml#L115), on [Imaginary Teleprompter](https://github.com/ImaginarySense/Imaginary-Teleprompter/blob/d476b29b393936375af73c82c6bb2a03e40fb18d/js/teleprompter.js#L452C9-L452C9), and [another teleprompter app I developed](https://github.com/Cuperino/teleprompter-for-terminals-april-fools-works/blob/fe3058edcf05bd80e9b6e033089d540e36c6500f/teleprompter-for-terminals.py#L168), I've used variations of the following equation:

```
speed = baseSpeed * ( |step| ^ accelerationCurvature )
velocity = speed * direction
milisecondsToReachEnd = (1000ms * travelDistance) / (speed * step)

step: Most people regard it as "speed", although it is not speed if the prompter can animate in reverse.
baseSpeed: a multiplier by, which can be automatically or manually adjusted based on the font's size relative to the screen
accelerationCurvature: a small exponent for the step, helps reach higher speeds with less steps. I've found a value of 1.3 makes a great default.
direction: -1 or 1 depending on which way you will animate
```

Given your project appears to follow Gnome's guidelines, I would advice hiding or not offering the ability to set the baseSpeed and accelerationCurve, and instead adjust for proportional animation speeds behind the scenes. In QPrompt I account for this by setting these additional factors at the base of the time calculation:
```
speed * step * fontSize / 2 * adjustedWidthOfTextBox
```
Resulting in:
```
milisecondsToReachEnd = (1000ms * travelDistance) / (speed * step * fontSize / 2 * adjustedWidthOfTextBox)
```

I hope this information is useful to you. Feel free to study my code to reference implementation details. it's all GPLv3, so feel free to derive from it under the same license. If you don't wish to derive, feel free to make use of the equations. These are mostly physics equations applied to teleprompters and therefore not copyrightable.

Cheers,
Javier
Author of [QPrompt Teleprompter](https://github.com/Cuperino/QPrompt-Teleprompter), co-author of [Imaginary Teleprompter](https://github.com/ImaginarySense/Imaginary-Teleprompter)

**Comment by Nokse22** [comment]
Thank you so much, these information are very useful to me.
I tried to find a formula to do this, but it wasn't easy, first I tried to do it empirically, but it didn't work.

For now I just did something like `speed = constant * user_speed * font_size / screen_width` similar to what you suggested, but I probably need to calibrate it better [(formula)](https://github.com/Nokse22/teleprompter/blob/385dbdb9b24823fc886ed73a1a55573a06882284/src/window.py#L312), because I present the speed setting in word per minute.
