### ISSUE TITLE
Make app icon perspective follow GNOME's guidelines

### ISSUE THREAD

**Issue by bragefuglseth** [Nokse22/teleprompter#3]
The app icon metaphor works great, and would look even more consistent with other GNOME apps if it was [geometrical and drawn in a birds-eye perspective](https://developer.gnome.org/hig/guidelines/app-icons.html). I'd suggest something similar to [Qwertone's](https://flathub.org/apps/com.gitlab.azymohliad.Qwertone) approach. Feel free to reach out to the [GNOME App Icon Design group](https://matrix.to/#/#appicondesign.gnome.org) on Matrix if you have any questions / want feedback 😁

**Comment by Nokse22** [comment]
Thank you for your feedback. I will try to make the app icon more consistent.
