### ISSUE TITLE
Crashes when I try to open file

### ISSUE THREAD

**Issue by Jeremi360** [Nokse22/teleprompter#39]
Really nice app, I tryied Qpromt before, 
but there is too many ui elements for something so simple like a telepromt app.
So I was happy when I discoverd your app.
But when I press open file button it crashes :disappointed: .
I think it is 'cose you devlop it for Gnome with out cosidering that non-gome user what to use it.
As I'm using Cinnamon instead of Gnome.
Go luck with your app, I hope you will fix this issui soon.

**Comment by Nokse22** [comment]
It's fixed, it was using the old way to open files.
