### ISSUE TITLE
No Italian translation 

### ISSUE THREAD

**Issue by albanobattistella** [Nokse22/teleprompter#40]
Hi,
After the last update, Italian translation is not available(see pictures)
Any ideas?
Thanks.
A.
![29](https://github.com/user-attachments/assets/4b2825af-137a-41fc-9fdf-91853061b6fe)
![29-1](https://github.com/user-attachments/assets/e8288b21-3b25-4420-8d33-fb32ddee9f2c)

**Comment by Nokse22** [comment]
I released a new version fixing all the translation issues
