### ISSUE TITLE
Turn scroll direction and rotate text

### ISSUE THREAD

**Issue by treborxy** [Nokse22/teleprompter#43]
Hello, thank you for the software that can handle even very long texts!
I still have a feature request:
When using the software with a camera (i.e. via a mirror), the text is not readable.
Therefore, it would be cool if the display and the scroll direction could be rotated.
Thank you

**Comment by Nokse22** [comment]
Hello, it seems like a reasonable feature for a teleprompter app to do. I will be adding this feature.
