### ISSUE TITLE
Preferences seems not translatable

### ISSUE THREAD

**Issue by sabriunal** [Nokse22/teleprompter#7]
Hi, I tried to translate Preferences strings but they did not accept translation.
![tr](https://github.com/Nokse22/teleprompter/assets/6218679/4207d491-103c-4d15-be6d-d7fb639beaa6)

[0001-App-Mark-preferences-strings-translatable.patch.txt](https://github.com/Nokse22/teleprompter/files/11738856/0001-App-Mark-preferences-strings-translatable.patch.txt)

**Comment by sabriunal** [comment]
As I reported 😁 It happened the same to me.

**Comment by sabriunal** [comment]
Change these lines (https://github.com/Nokse22/teleprompter/blob/main/io.github.nokse22.teleprompter.json#L31-L34)

Use

"type" : "dir",
"path" : "."

May have read the source code from the git repository.

**Comment by Nokse22** [comment]
Thank you, now it works. Also I fixed the preference window not getting translated. [This](https://github.com/Nokse22/teleprompter/blob/72d28f811285d60fe95362416946a42f9d38a584/src/main.py#L34C1-L37) was missing

**Comment by sabriunal** [comment]
I should have known it. I had fixed the same issue before. :(
