### ISSUE TITLE
Don't make the text invisible

### ISSUE THREAD

**Issue by sabriunal** [Nokse22/teleprompter#8]
Hello, if the text size is reduced excessively, it may become invisible. Let's make sure to maintain an appropriate size to ensure readability.

[invisible.webm](https://github.com/Nokse22/teleprompter/assets/6218679/0dd6ba3a-cd76-4f95-851a-9016fad46f04)

**Comment by Nokse22** [comment]
fixed with https://github.com/Nokse22/teleprompter/commit/fdbe0303114990db03e708c3ecf772badcfd97de
